<?php /* @var $this Mage_Adminhtml_Block_Template */ ?>
<p><?php echo $this->escapeHtml($this->__('From this page you can see previous translation requests or start a new request.')) ?></p>
<p><?php echo $this->escapeHtml($this->__('A translation request may have any of the following statuses:')) ?></p>
<ul>
    <li><strong><?php echo $this->escapeHtml($this->__('In Progress')) ?>:</strong>
    <?php echo $this->escapeHtml($this->__('The request is currently being translated by Capita Translation and Interpreting.')) ?></li>
    <li><strong><?php echo $this->escapeHtml($this->__('On Hold')) ?>:</strong>
    <?php echo $this->escapeHtml($this->__('The translation has not yet started.')) ?></li>
    <li><strong><?php echo $this->escapeHtml($this->__('Importing')) ?>:</strong>
    <?php echo $this->escapeHtml($this->__('The translation has finished and will be in place shortly.')) ?></li>
    <li><strong><?php echo $this->escapeHtml($this->__('Completed')) ?>:</strong>
    <?php echo $this->escapeHtml($this->__('The translation was successfully imported.')) ?></li>
</ul>
<p><?php echo $this->escapeHtml($this->__('If any request has a status of "On Hold" or "In Progress" then you may click "Refresh Status" and Magento will check each with Capita Translation and Interpreting.')) ?></p>
<p><img src="<?php echo $this->getSkinUrl('images/capita/requests-screenshot.png') ?>" alt="<?php echo $this->escapeHtml($this->__('Translation Requests')) ?>"></p>
